spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Admin
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}
