spring.application.name=backend

spring.datasource.url=jdbc:mariadb://localhost:3306/devlog
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

#개발
#spring.jpa.show-sql=true

#운영
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

# Admin
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}

spring.profiles.active=local
